import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { ArrowForward } from "@mui/icons-material";
import { Paper, Typography, Box, Button } from "@mui/material";
import { AnimatePresence, motion } from "framer-motion";

import { api } from "@/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // stagger animation variant
  const stagger = {
    animate: {
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  // fade in animation variant
  const fadeInUp = {
    initial: {
      y: 60,
      opacity: 0,
    },
    animate: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.6,
        ease: [0.48, 0.15, 0.25, 0.96],
      },
    },
  };

  return (
    <>
      <Head>
        <title>T3Realtors</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence mode="wait" key={router.pathname}>
        <Paper
          className={styles.main}
          component={"main"}
          sx={{
            background: (theme) =>
              `linear-gradient(
              180deg,
              ${
                theme.palette.mode === "dark"
                  ? "rgb(0, 0, 0)"
                  : "rgb(204, 222, 230)"
              } 0%,
              ${
                theme.palette.mode === "dark"
                  ? "rgba(0, 0, 0, 0.492)"
                  : "rgba(173, 232, 236, 0.492)"
              } 100%
            ),
            url('/img/real-estate-hero-bg.jpeg')
              center center / cover no-repeat`,
          }}
        >
          <Box
            sx={{
              maxWidth: 600,
            }}
            component={motion.div}
            variants={stagger}
            initial="initial"
            animate="animate"
          >
            <Typography
              variant="h1"
              gutterBottom
              component={motion.h1}
              variants={fadeInUp}
            >
              Find Real Estate That Suits you
            </Typography>
            <Typography gutterBottom component={motion.p} variants={fadeInUp}>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa
              omnis debitis voluptates harum, voluptatibus magnam molestiae. Vel
              vero quibusdam repellendus.
            </Typography>
            <Typography
              color="inherit"
              gutterBottom
              component={motion.p}
              variants={fadeInUp}
            >
              <code>{hello.data?.greeting}</code>
            </Typography>
            <Button
              variant="contained"
              sx={{ mt: 2 }}
              endIcon={<ArrowForward />}
              component={motion.a}
              variants={fadeInUp}
            >
              Get Started
            </Button>
          </Box>
        </Paper>
      </AnimatePresence>
    </>
  );
};

export default Home;
