import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { ArrowForward } from "@mui/icons-material";
import { Paper, Typography, Box, Button } from "@mui/material";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>T3Realtors</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper
        className={styles.main}
        component={"main"}
        sx={{
          background: (theme) =>
            `linear-gradient(
              180deg,
              ${
                theme.palette.mode === "dark"
                  ? "rgb(0, 0, 0)"
                  : "rgb(222, 233, 238)"
              } 0%,
              ${
                theme.palette.mode === "dark"
                  ? "rgba(0, 0, 0, 0.492)"
                  : "rgba(173, 232, 236, 0.492)"
              } 100%
            ),
            url('/img/real-estate-hero-bg.jpeg')
              center center / cover no-repeat`,
        }}
      >
        <Box
          sx={{
            maxWidth: 600,
          }}
        >
          <Typography variant="h1" gutterBottom>
            Find Real Estate That Suits you
          </Typography>
          <Typography gutterBottom>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa omnis
            debitis voluptates harum, voluptatibus magnam molestiae. Vel vero
            quibusdam repellendus.
          </Typography>
          <Typography color="inherit" gutterBottom>
            <code>{hello.data?.greeting}</code>
          </Typography>
          <Button variant="contained" sx={{ mt: 2 }} endIcon={<ArrowForward />}>
            Get Started
          </Button>
        </Box>
      </Paper>
    </>
  );
};

export default Home;
